### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by lucastle6969** [lucastle6969/AntennaPod390#101]
As a user, I want to be able to categorize my podcasts, so that I can organize my podcasts by category or to my liking, instead of having them all in one big list.

- [x] acceptance test
- [x] (new) layout for podcast subscriptions page and inner layout for category (handle option to view all podcasts, view specific category or view all podcasts by category, option to add/delete/modify category) + UI tests [ #128 ]
- [x]  layout and implementation for long click : add podcast to category + UI tests [ #127 #126 ]
- [x] category crud operations (manage categories, add, modify, delete db operations) + unit tests [ #121 #130 #132 ]
- [x] implement front-end for add, modify, delete categories [ #126 #127 #130 #132]

[Story Points: 40]
[Risk: High]
[Priority: Low]
