### ISSUE TITLE
Achievements - My Achievements

### ISSUE THREAD

**Issue by lucastle6969** [lucastle6969/AntennaPod390#103]
As a user, I want to be able to unlock achievements, so I can learn about the apps features in an engaging and exciting manner.

- [x] layout for My Achievements page (+ UI tests) [ #185 ]
- [x] crud / db operations for acheivements (+ unit tests) [ #179 ] 
- [x] implement system to monitor for initial set of achievements (+ unit tests) [ #186 ]
- [x] implement dialogs, feedback (audio / visual) for unlocking achievement (+ UI tests) [ #187 ]
- [x] acceptance test

[Story Points: 16]
[Risk: Low]
[Priority: High]
