### ISSUE TITLE
Unified search layout between providers 

### ISSUE THREAD

**Issue by lucastle6969** [lucastle6969/AntennaPod390#28]
As a user, I want all of my providers to look the same, so I can intuitively know how to find podcasts in either one.

- [x] implementation of the unified view for iTunes [#18] @kjanei 
- [x] implementation of the unified view for Fyyd [#30] @vineetkoppalkar , @Mstc08 
- [x] implementation of the unified view for gpodder [#31] @lucastle6969 
- [x] acceptance tests @PetiaPav , @dfeokti , @Michael-Gagnon 

[Story Points :  30 ]
[Risk :  low ]
[Priority :  high ]
