### ISSUE TITLE
Mockups for sprint 2

### ISSUE THREAD

**Issue by lucastle6969** [lucastle6969/AntennaPod390#29]
As a developer, I want to have mockups for my new features, so I can have a specific plan to work towards.

- [x] Mockup of new Side Menu ordering #12 
- [x] Mockup for unified view of each search provider #11 
- [x] Mockup for new search layout #8 

Story Points : 3
Priority: High
Risk: Low
