### ISSUE TITLE
Add Bookmarks

### ISSUE THREAD

**Issue by lucastle6969** [lucastle6969/AntennaPod390#37]
As a user, I'd like to be able to place a marker at certain key points in a podcast, so I can come back to it later.

- [x] acceptance tests design
- [x] Audio Player Layout with new bookmark button and listner functionalities (+ UI test) [ #79 ]
- [x] Store new Bookmark data (+ unit test) [ #80 ] 
- [x] data structure for storing bookmarks (+ unit test) [ #81 ]
- [x] acceptance testing

[Story Points :  25]
[Risk : High]
[Priority : High]
