### ISSUE TITLE
Improved UI Design

### ISSUE THREAD

**Issue by vineetkoppalkar** [lucastle6969/AntennaPod390#7]
As a developer, I would like to improve the UI for key activities in the app. The current search layout is not intuitive to new users. The current menu elements' ordering is not intuitive to users.

Related Stories :
- [ ] Improved Search UI - Phase 1 [#10]
- [ ] Improved Search UI - Phase 2 [#13]
- [ ] Improved Menu UI  [#9]
